cqhttpConfig:
  IpAddress: "127.0.0.1"
  Port: 6700
  Token: ""

MashiroConfig:
  ReactGroup: 114514
  SendingStackDepth: 10
  SendingInterval: 1

ParseConfig:
  Parser: "BuiltIn"

CommandConfig:
  CommandIdentifier:
    - "!!"
    - "！！"
  MaxResponseTime: 6

PluginConfig:
  PluginPath: "./plugins"

DebugConfig:
  LogLevel: "DEBUG"
